export function printElement(title: string, contentHtml: string) {
  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) return;
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; padding: 40px; color: #1e293b; font-size: 13px; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; padding-bottom: 20px; border-bottom: 2px solid #2563eb; }
        .logo { font-size: 22px; font-weight: 800; color: #2563eb; }
        .logo-sub { font-size: 11px; color: #94a3b8; margin-top: 2px; }
        .title { font-size: 20px; font-weight: 700; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #f8fafc; padding: 10px 12px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; border-bottom: 1px solid #e2e8f0; }
        td { padding: 10px 12px; border-bottom: 1px solid #f1f5f9; }
        .total-row td { font-weight: 700; background: #f8fafc; border-top: 2px solid #e2e8f0; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 11px; font-weight: 600; }
        .badge-green { background: #dcfce7; color: #16a34a; }
        .badge-blue  { background: #dbeafe; color: #2563eb; }
        .badge-red   { background: #fee2e2; color: #dc2626; }
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 24px; }
        .info-box { background: #f8fafc; border-radius: 8px; padding: 14px; }
        .info-label { font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
        .info-value { font-weight: 600; font-size: 14px; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <div class="header">
        <div><div class="logo">⚡ ERP System</div><div class="logo-sub">Enterprise Edition</div></div>
        <div style="text-align:right;color:#94a3b8;font-size:12px;">${new Date().toLocaleDateString()}<br/>${new Date().toLocaleTimeString()}</div>
      </div>
      ${contentHtml}
      <div class="footer">Generated by ERP System · ${new Date().toLocaleString()}</div>
    </body>
    </html>
  `);
  win.document.close();
  setTimeout(() => { win.print(); }, 500);
}

export function generateInvoicePDF(invoice: any, lines: any[], payments: any[]) {
  const linesHtml = lines.map(l => `
    <tr>
      <td>${l.sku ?? ""}</td>
      <td>${l.name ?? ""}</td>
      <td style="text-align:center">${l.qty}</td>
      <td style="text-align:right">$${Number(l.unit_price ?? l.unit_cost ?? 0).toFixed(2)}</td>
      <td style="text-align:right;font-weight:600">$${Number(l.line_total ?? 0).toFixed(2)}</td>
    </tr>
  `).join("");

  const paymentsHtml = payments.length > 0 ? `
    <div class="title" style="font-size:14px;margin-top:20px">Pagos Registrados</div>
    <table>
      <thead><tr><th>Fecha</th><th>Metodo</th><th style="text-align:right">Monto</th></tr></thead>
      <tbody>${payments.map(p => `<tr><td>${new Date(p.paid_at).toLocaleString()}</td><td>${p.method}</td><td style="text-align:right">$${Number(p.amount).toFixed(2)}</td></tr>`).join("")}</tbody>
    </table>
  ` : "";

  const html = `
    <div class="title">Factura</div>
    <div class="info-grid">
      <div class="info-box"><div class="info-label">Cliente</div><div class="info-value">${invoice.customer_name}</div></div>
      <div class="info-box"><div class="info-label">Estado</div><div class="info-value">${invoice.status}</div></div>
      <div class="info-box"><div class="info-label">Total</div><div class="info-value">$${Number(invoice.total ?? 0).toFixed(2)}</div></div>
      <div class="info-box"><div class="info-label">Saldo</div><div class="info-value" style="color:#dc2626">$${Number(invoice.balance_due ?? 0).toFixed(2)}</div></div>
    </div>
    <table>
      <thead><tr><th>SKU</th><th>Producto</th><th style="text-align:center">Cant.</th><th style="text-align:right">Precio</th><th style="text-align:right">Total</th></tr></thead>
      <tbody>${linesHtml}</tbody>
      <tr class="total-row"><td colspan="4" style="text-align:right;padding:10px 12px">TOTAL</td><td style="text-align:right;padding:10px 12px">$${Number(invoice.total ?? 0).toFixed(2)}</td></tr>
    </table>
    ${paymentsHtml}
  `;
  printElement("Factura — " + invoice.customer_name, html);
}

export function generatePOPDF(po: any, lines: any[]) {
  const linesHtml = lines.map(l => `
    <tr>
      <td>${l.sku ?? ""}</td>
      <td>${l.name ?? ""}</td>
      <td style="text-align:center">${l.qty}</td>
      <td style="text-align:right">$${Number(l.unit_cost ?? 0).toFixed(2)}</td>
      <td style="text-align:right;font-weight:600">$${Number(l.line_total ?? 0).toFixed(2)}</td>
    </tr>
  `).join("");

  const html = `
    <div class="title">Orden de Compra</div>
    <div class="info-grid">
      <div class="info-box"><div class="info-label">Proveedor</div><div class="info-value">${po.vendor_name}</div></div>
      <div class="info-box"><div class="info-label">Estado</div><div class="info-value">${po.status}</div></div>
      <div class="info-box"><div class="info-label">Total</div><div class="info-value">$${Number(po.total ?? 0).toFixed(2)}</div></div>
      <div class="info-box"><div class="info-label">Fecha</div><div class="info-value">${new Date(po.created_at).toLocaleDateString()}</div></div>
    </div>
    <table>
      <thead><tr><th>SKU</th><th>Producto</th><th style="text-align:center">Cant.</th><th style="text-align:right">Costo Unit.</th><th style="text-align:right">Total</th></tr></thead>
      <tbody>${linesHtml}</tbody>
      <tr class="total-row"><td colspan="4" style="text-align:right;padding:10px 12px">TOTAL</td><td style="text-align:right;padding:10px 12px">$${Number(po.total ?? 0).toFixed(2)}</td></tr>
    </table>
  `;
  printElement("OC — " + po.vendor_name, html);
}

export function generatePayrollPDF(run: any, lines: any[]) {
  const linesHtml = lines.map(l => `
    <tr>
      <td>${l.employee_name}</td>
      <td>${l.department ?? "—"}</td>
      <td style="text-align:right">$${Number(l.gross_salary ?? 0).toFixed(2)}</td>
      <td style="text-align:right;color:#dc2626">$${Number(l.tax_amount ?? 0).toFixed(2)}</td>
      <td style="text-align:right;color:#dc2626">$${Number(l.other_deductions ?? 0).toFixed(2)}</td>
      <td style="text-align:right;font-weight:700;color:#16a34a">$${Number(l.net_pay ?? 0).toFixed(2)}</td>
    </tr>
  `).join("");
  const totalNet = lines.reduce((s, l) => s + Number(l.net_pay ?? 0), 0);

  const html = `
    <div class="title">Nomina — ${run.period_start} al ${run.period_end}</div>
    <div class="info-grid">
      <div class="info-box"><div class="info-label">Periodo</div><div class="info-value">${run.period_start} → ${run.period_end}</div></div>
      <div class="info-box"><div class="info-label">Estado</div><div class="info-value">${run.status}</div></div>
      <div class="info-box"><div class="info-label">Empleados</div><div class="info-value">${run.employee_count}</div></div>
      <div class="info-box"><div class="info-label">Total Neto</div><div class="info-value" style="color:#16a34a">$${Number(run.total_net ?? 0).toFixed(2)}</div></div>
    </div>
    <table>
      <thead><tr><th>Empleado</th><th>Dept.</th><th style="text-align:right">Bruto</th><th style="text-align:right">Impuesto</th><th style="text-align:right">Deducciones</th><th style="text-align:right">Neto</th></tr></thead>
      <tbody>${linesHtml}</tbody>
      <tr class="total-row"><td colspan="5" style="text-align:right;padding:10px 12px">TOTAL NETO</td><td style="text-align:right;padding:10px 12px;color:#16a34a">$${totalNet.toFixed(2)}</td></tr>
    </table>
  `;
  printElement("Nomina — " + run.period_start, html);
}